addEvent("playerKnock", true)
addEventHandler("playerKnock", root, function(x, y, z)
	outputChatBox("* Kapıdan tıkırtılar geliyor. ((" .. getPlayerName(source):gsub("_", " ") .. "))", 255, 51, 102)
	local sound = playSound3D("public/sounds/knocking.mp3", x, y, z)
	setSoundMaxDistance(sound, 20)
	setElementDimension(sound, getElementDimension(localPlayer))
	setElementInterior(sound, getElementInterior(localPlayer))
end)

addEvent("doorUnlockSound", true)
addEventHandler("doorUnlockSound", root, function(x, y, z)
	local sound = playSound3D("public/sounds/doorUnlockSound.mp3", x, y, z)
	setSoundMaxDistance(sound, 20)
	setElementDimension(sound, getElementDimension(localPlayer))
	setElementInterior(sound, getElementInterior(localPlayer))
end)

addEvent("doorLockSound", true)
addEventHandler("doorLockSound", root, function(x, y, z)
	local sound = playSound3D("public/sounds/doorLockSound.mp3", x, y, z)
	setSoundMaxDistance(sound, 20)
	setElementDimension(sound, getElementDimension(localPlayer))
	setElementInterior(sound, getElementInterior(localPlayer))
end)

addEvent("doorGoThru", true)
addEventHandler("doorGoThru", root, function(x, y, z)
	local sound = playSound3D("public/sounds/doorGoThru.mp3", x, y, z)
	setSoundMaxDistance(sound, 20)
	setElementDimension(sound, getElementDimension(localPlayer))
	setElementInterior(sound, getElementInterior(localPlayer))
	setSoundVolume(sound, 0.5)
end)
